import { useState } from "react";

import type { ChatSessionRow } from "@backend/types/database";
import { CircleNotchIcon, SparkleIcon } from "@phosphor-icons/react";
import { Link, useRouterState } from "@tanstack/react-router";

import { Skeleton } from "@/components/ui/skeleton";
import { useRepositoryListQuery } from "@/contexts/RepositoryContext";
import { api } from "@/lib/api";
import { relativeTime } from "@/lib/relative-time";

import { ChatContextMenu, type ChatContextMenuState } from "./ChatContextMenu";

export function ChatList() {
  const activeChatId = useRouterState({
    select: (s) => s.location.pathname.match(/^\/dashboard\/chats\/([^/]+)$/)?.[1],
  });
  const [menu, setMenu] = useState<ChatContextMenuState | null>(null);

  const { records: sessions, status } = useRepositoryListQuery(
    "chat_sessions",
    undefined,
    {
      order: (a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime(),
    },
    async () => await api.fetch("/api/chat", "GET"),
  );

  const loading = status === "fetching" && sessions.length === 0;
  const count = loading ? "…" : sessions.length;

  return (
    <aside className="flex w-80 shrink-0 flex-col border-r border-amber bg-background">
      <div className="hud-subheader px-5">
        <span className="hud-label">SESSIONS [{count}]</span>
      </div>
      <div className="min-h-0 flex-1 overflow-auto">
        {loading ? (
          <ChatListSkeletons />
        ) : sessions.length === 0 ? (
          <EmptyHint>NO SESSIONS. TYPE BELOW TO INITIALIZE.</EmptyHint>
        ) : (
          sessions.map((session) => (
            <ChatListItem
              key={session.id}
              session={session}
              onContextMenu={(e) => {
                e.preventDefault();
                setMenu({ id: session.id, x: e.clientX, y: e.clientY });
              }}
            />
          ))
        )}
      </div>
      <ChatContextMenu
        state={menu}
        activeChatId={activeChatId}
        onClose={() => setMenu(null)}
      />
    </aside>
  );
}

function ChatListSkeletons() {
  return (
    <div>
      {Array.from({ length: 6 }).map((_, i) => (
        <div key={i} className="flex flex-col gap-1.5 border-b border-amber-hair px-5 py-3">
          <div className="flex items-center justify-between gap-2">
            <Skeleton className="h-3.5 min-w-0 flex-1" />
            <Skeleton className="h-3 w-12 shrink-0" />
          </div>
        </div>
      ))}
    </div>
  );
}

function EmptyHint({ children }: { children: React.ReactNode }) {
  return <div className="px-5 py-6 hud-caption">{children}</div>;
}

function ChatListItem({
  session,
  onContextMenu,
}: {
  session: ChatSessionRow;
  onContextMenu: (e: React.MouseEvent) => void;
}) {
  return (
    <Link
      to="/dashboard/chats/$chatId"
      params={{ chatId: session.id }}
      onContextMenu={onContextMenu}
      className="block border-b border-amber-hair selectable-button-accent-1 px-5 py-3"
    >
      <div className="flex items-center justify-between gap-2">
        <div className="flex min-w-0 flex-1 items-center gap-1.5">
          {session.kind === "internal" && <InternalBadge />}
          <ChatTitle title={session.title} />
        </div>
        <time
          className="shrink-0 text-mint tabular-nums"
          style={{ fontSize: "0.625rem", letterSpacing: "0.04em", textTransform: "uppercase" }}
        >
          {relativeTime(new Date(session.updated_at))}
        </time>
      </div>
      {session.is_generating && (
        <p
          className="mt-1 flex items-center gap-1.5 text-mint"
          style={{ fontSize: "0.625rem", letterSpacing: "0.08em", textTransform: "uppercase" }}
        >
          <span className="animate-hud-blink" aria-hidden>▪</span>
          GENERATING…
        </p>
      )}
    </Link>
  );
}

function InternalBadge() {
  return (
    <span
      title="Auto-generated by an internal process"
      className="inline-flex shrink-0 items-center gap-0.5 border border-mint-dim px-1 py-0 text-mint"
      style={{ fontSize: "0.5625rem", letterSpacing: "0.08em", textTransform: "uppercase" }}
    >
      <SparkleIcon size={9} weight="fill" />
      AUTO
    </span>
  );
}

function ChatTitle({ title }: { title: string | null }) {
  if (title === null) {
    return (
      <span className="inline-flex min-w-0 items-center gap-1.5 truncate text-text-3 italic" style={{ fontSize: "0.75rem" }}>
        <CircleNotchIcon size={12} className="shrink-0 animate-hud-tick" />
        GENERATING TITLE…
      </span>
    );
  }
  return (
    <h3
      className="truncate"
      style={{ fontSize: "0.75rem", fontWeight: 600, letterSpacing: "0.04em", textTransform: "uppercase" }}
    >
      {title}
    </h3>
  );
}
