name: CI

on:
  push:
    branches:
      - main
      - "**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build & Lint & Test backend
            command: ./packages/backend/scripts/build-types.ts && ./packages/backend/scripts/lint.ts && npm test -w backend
          - name: Build & Lint & Test frontend
            command: ./packages/backend/scripts/build-types.ts && ./packages/frontend/scripts/build-types.ts && ./packages/frontend/scripts/lint.ts && npm test -w frontend
          - name: Build & Lint e2e
            command: ./scripts/e2e_build_types.ts && ./scripts/e2e_lint.ts
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: ${{ matrix.command }}
